/**
 * KaTeX inputs. Backslashes MUST NOT appear as `\` in string literals: Vite/Rolldown
 * minifies them into template literals and doubles escapes in production, breaking KaTeX.
 * Use `bs` (ASCII 92) interpolated into templates instead.
 */
const bs = String.fromCharCode(92)

export const bt = {
  rSeq: `${bs}{r_t${bs}}_{t=1}^{N}`,
  def31: `V_t = V_0 + ${bs}sum_{i=1}^{t} r_i ${bs}cdot c_i - ${bs}sum_{i=1}^{t} ${bs}phi_i`,
  def32: `DD_t = ${bs}frac{${bs}max_{s ${bs}leq t} V_s - V_t}{${bs}max_{s ${bs}leq t} V_s}, ${bs}quad MDD = ${bs}max_{t ${bs}in [0,T]} DD_t`,
  def33: `${bs}text{CAGR} = ${bs}left(${bs}frac{V_T}{V_0}${bs}right)^{1/T} - 1`,
  def34: `${bs}mathcal{S} = ${bs}frac{${bs}bar{r}}{${bs}hat{${bs}sigma}_r} ${bs}cdot ${bs}sqrt{f}, ${bs}quad f = ${bs}frac{N}{T}`,
  def35: `${bs}mathcal{D} = ${bs}frac{${bs}bar{r}}{${bs}sigma_d} ${bs}cdot ${bs}sqrt{f}, ${bs}quad ${bs}sigma_d = ${bs}sqrt{${bs}frac{1}{N}${bs}sum_{i=1}^{N} ${bs}min(r_i, 0)^2}`,
  mes5: `${bs}$5${bs}text{ por ponto}`,
  mnq2: `${bs}$2${bs}text{ por ponto}`,
  pipe41: `${bs}{t_{${bs}text{open}},${bs}, P_{${bs}text{open}},${bs}, P_{${bs}text{high}},${bs}, P_{${bs}text{low}},${bs}, P_{${bs}text{close}},${bs}, V${bs}}`,
  pipe42a: `(P_{${bs}text{entry}},${bs}, t_{${bs}text{entry}})`,
  pipe42b: `(P_{${bs}text{exit}},${bs}, t_{${bs}text{exit}})`,
  pipe43a: `r_i^{${bs}text{gross}} = ${bs}Delta P_i ${bs}cdot ${bs}text{ptval} ${bs}cdot c_i`,
  pipe43b: `${bs}phi = ${bs}$0{,}62`,
  pipe43c: `r_i = r_i^{${bs}text{gross}} - c_i ${bs}cdot ${bs}phi`,
  pipe44a: `${bs}{r_i${bs}}`,
  pipe44b: 'B = 10{,}000',
  pipe44c: `(${bs}mu, ${bs}sigma, ${bs}text{win rate})`,
  vtBh: `V_t^{${bs}text{BH}}`,
  v0k: `V_0 = ${bs}$10{,}000`,
  ddCaption: `DD_t = (${bs}max_{s ${bs}leq t} V_s - V_t)${bs},/${bs},${bs}max_{s ${bs}leq t} V_s`,
  metricCagr: `${bs}text{CAGR}`,
  metricS: `${bs}mathcal{S}`,
  metricD: `${bs}mathcal{D}`,
  o61a: `N_{${bs}text{ES}} = 4{.}620`,
  o61b: `N_{${bs}text{NQ}} = 4{.}343`,
  o61c: `${bs}text{SE}(${bs}hat{p}) = ${bs}sqrt{${bs}hat{p}(1-${bs}hat{p})/N} ${bs}approx 0{,}007`,
  o61d: `${bs}pm 1{,}4${bs}%`,
  o62a: `${bs}mathbb{E}[${bs}text{win}] ${bs}approx |${bs}mathbb{E}[${bs}text{loss}]|`,
  o62b: `${bs}bar{w} = 10{,}58${bs}text{ pts},${bs};${bs}bar{l} = -10{,}41${bs}text{ pts}`,
  o62c: `${bs}bar{w} = 48{,}94${bs}text{ pts},${bs};${bs}bar{l} = -47{,}42${bs}text{ pts}`,
  o62d: `${bs}bar{w}/|${bs}bar{l}| ${bs}approx 1{,}02`,
  o63a: `${bs}text{PF} = 1{,}46`,
  o63b: `${bs}text{PF} = 1{,}41`,
  o632a: `${bs}hat{${bs}mu}_{${bs}text{NQ}}`,
  o632b: `${bs}hat{${bs}sigma}_{${bs}text{NQ}}`,
  o63delta: `${bs}delta`,
  kE: `K ${bs}cdot ${bs}mathbb{E}[r]`,
  rho: `${bs}rho ${bs}in [0,1]`,
  def631: `P(${bs}text{Loss}_{${bs}text{sessão}} ${bs}mid K) = (1 - p)^K`,
  pLoss: `P(${bs}text{Loss}_{${bs}text{sessão}})`,
  def632: `(1-p)^K ${bs};${bs}leq${bs}; P(${bs}text{Loss}_{${bs}text{sessão}}) ${bs};${bs}leq${bs}; (1-p), ${bs}quad ${bs}rho ${bs}in [0, 1]`,
  limDelta: `${bs}delta`,
  limMu: `${bs}hat{${bs}mu}`,
  limSigma: `${bs}hat{${bs}sigma}`,
} as const

export const sp = {
  abstractR2: `R^2_{${bs}text{OOS}} ${bs}approx 0.40`,
  rLog: `r_t = ${bs}log(P_t / P_{t-1})`,
  rvH: `${bs}text{RV}_h = ${bs}sqrt{${bs}frac{252}{h} ${bs}sum_{i=1}^{h} r_{t-i}^2}`,
  yTarget: `${bs}hat{y}_{t,h} = ${bs}log${bs}!${bs}left(${bs}text{RV}_h^{${bs}text{forward}}${bs}right), ${bs}quad ${bs}text{RV}_h^{${bs}text{forward}} = ${bs}sqrt{${bs}frac{252}{h}${bs}sum_{i=1}^{h} r_{t+i}^2}`,
  vrp: `${bs}text{VRP}`,
  vrpFormula: `${bs}text{VRP}_t = ${bs}text{IV}_t^2 - ${bs}text{RV}_{22,t}^2`,
  r2oos: `R^2_{${bs}text{OOS}} = 1 - ${bs}frac{${bs}sum_{t}(y_t - ${bs}hat{y}_t)^2}{${bs}sum_{t}(y_t - ${bs}bar{y})^2}`,
  ttGSPC: `${bs}texttt{${bs}^{}GSPC}`,
  ttVIX: `${bs}texttt{${bs}^{}VIX}`,
  ttVIX9D: `${bs}texttt{${bs}^{}VIX9D}`,
  ttVIX3M: `${bs}texttt{${bs}^{}VIX3M}`,
  ttVIX6M: `${bs}texttt{${bs}^{}VIX6M}`,
  ttSKEW: `${bs}texttt{${bs}^{}SKEW}`,
  feat41: `${bs}text{VIX}_{9d},${bs}, ${bs}text{VIX}_{30d},${bs}, ${bs}text{VIX}_{3m},${bs}, ${bs}text{VIX}_{6m}`,
  feat42: `${bs}text{VIX}_{3m} - ${bs}text{VIX}_{9d}`,
  feat44a: `${bs}text{RV}_5`,
  feat44b: `${bs}text{RV}_{22}`,
  feat44c: `${bs}text{RV}_5 / ${bs}text{RV}_{22}`,
  feat45a: `${bs}text{VRP}_{30d}`,
  feat45b: `${bs}text{VRP}_{${bs}text{short}}`,
  pipeR2oos: `R^2_{${bs}text{OOS}}`,
  naiveY: `${bs}hat{y}_t = ${bs}log(${bs}text{VIX}_t / 100)`,
  harFeats: `${bs}log(${bs}text{RV}_5),${bs}, ${bs}log(${bs}text{RV}_{22}),${bs}, ${bs}log(${bs}text{VIX}),${bs}, ${bs}text{VRP}_{30d},${bs}, ${bs}text{SKEW}`,
  ell1: `${bs}ell_1`,
  dmax: `d_{${bs}max}=4`,
  ensR2: `R^2_{${bs}text{OOS}}`,
  tsSplit: `${bs}mathcal{D}_k^{${bs}text{train}} = ${bs}{(x_t, y_t)${bs}}_{t=1}^{T_k}, ${bs}quad ${bs}mathcal{D}_k^{${bs}text{test}} = ${bs}{(x_t, y_t)${bs}}_{t=T_k+1}^{T_k + ${bs}Delta}`,
  metricR2: `R^2_{${bs}text{OOS}}`,
  metricMAE: `${bs}text{MAE}`,
  metricF: `|${bs}mathcal{F}|`,
  res556a: `R^2_{${bs}text{OOS}} ${bs}approx 0.40`,
  res556b: `R^2_{${bs}text{OOS}} > 0.20`,
  shapLog: `${bs}log(${bs}text{RV}_{22})`,
  shapVRP: `${bs}text{VRP}_{30d}`,
  final604: `R^2_{${bs}text{OOS}} ${bs}approx 0.40`,
} as const
